### ISSUE TITLE
Can't modify Form Designers

### ISSUE THREAD

**Issue by NLK511** [Ericmas001/BluffinMuffin.Client#9]
It seems that there is no way to correctly visualize the designers of TableForm and TableViewerForm. Visual Studio show instead an error:
 "The designer could not be shown for this file because none of the classes within it can be designed"

**Comment by Ericmas001** [comment]
What version of visual studio are you using. I just tried and everything is working for me. I tried on another computer with a different version and it's still working. The problem is probably on your VS configuration, or you are using an older version. It should at least work with VS2013 and VS2015.
